remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Juan Martinez-Piazuelo]
description: [Ph.D. in Automatic Control with expertise in optimization, machine learning, control systems, and game theory. Experienced in research and industry collaboration, seeking to apply my technical skills to solve real-world challenges.]